In [1]:
import os
import sys
import pandas as pd

In [2]:
def sMAPE(predictions, actuals):
    return ((predictions - actuals).abs() / (predictions.abs() + actuals.abs())).mean()

In [9]:
def read_test_files(benchmark_dir):
    
    test_data_dir = os.path.join(benchmark_dir, "data", "test")
    for rnd in range(1, 13):
        test_file = 'test_round_'+str(rnd)+'.csv'
        test_round = pd.read_csv(os.path.join(test_data_dir, test_file))
        test_round['round'] = rnd
        #test_round = test_round[['round', 'store', 'brand', 'week', 'logmove']]
        if rnd > 1:
            test = test.append(test_round)
        else:
            test = test_round.copy()
    return test

In [10]:
test = read_test_files(os.path.join('.', '..'))

In [11]:
test.head()

,brand,week,logmove,constant,price1,price2,price3,price4,price5,price6,price7,price8,price9,price10,price11,deal,feat,profit,round
0,1,137,9.189321,1,0.041645,0.051979,0.047656,0.038801,0.032656,0.038125,0.032861,0.036094,0.037344,0.022187,0.032422,0,0.0,20.425098,1
1,1,138,9.738613,1,0.037344,0.038958,0.047656,0.035781,0.043594,0.050937,0.042031,0.038906,0.037344,0.031094,0.032422,1,1.0,11.290000,1
2,2,137,8.738735,1,0.041645,0.051979,0.047656,0.038801,0.032656,0.038125,0.032861,0.036094,0.037344,0.022187,0.032422,0,0.0,33.300308,1
3,2,138,9.601301,1,0.037344,0.038958,0.047656,0.035781,0.043594,0.050937,0.042031,0.038906,0.037344,0.031094,0.032422,1,1.0,9.430000,1
4,3,137,7.560080,1,0.041645,0.051979,0.047656,0.038801,0.032656,0.038125,0.032861,0.036094,0.037344,0.022187,0.032422,0,0.0,30.506667,1

In [13]:
sales = pd.read_csv(os.path.join('.', '..', 'data', 'yx.csv'), index_col=0)

In [14]:
sales.head()

,brand,week,logmove,constant,price1,price2,price3,price4,price5,price6,price7,price8,price9,price10,price11,deal,feat,profit
store,,,,,,,,,,,,,,,,,,
2,1,40,9.018695,1,0.060469,0.060497,0.042031,0.029531,0.049531,0.053021,0.038906,0.041406,0.028906,0.024844,0.038984,1,0.0,37.992326
2,1,46,8.723231,1,0.060469,0.060312,0.045156,0.046719,0.049531,0.047813,0.045781,0.027969,0.042969,0.042031,0.038984,0,0.0,30.126667
2,1,47,8.253228,1,0.060469,0.060312,0.045156,0.046719,0.037344,0.053021,0.045781,0.041406,0.048125,0.032656,0.038984,0,0.0,30.000000
2,1,48,8.987197,1,0.060469,0.060312,0.049844,0.037344,0.049531,0.053021,0.045781,0.041406,0.042344,0.032656,0.038984,0,0.0,29.950000
2,1,50,9.093357,1,0.060469,0.060312,0.043594,0.031094,0.049531,0.053021,0.046648,0.041406,0.042344,0.032656,0.038203,0,0.0,29.920000

In [ ]:
      data.frame(round = rep(r, dim(test_df)[1]),
                 store = test_df$store,
                 brand = test_df$brand,
                 week = test_df$week,
                 truth = round(exp(test_df$logmove)))